[tool.black]
# Black code formatter configuration
line-length = 90
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | __pycache__
  | build
  | dist
  | migrations
  | alembic/versions
)/
'''

[tool.isort]
# isort import sorter configuration
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 90
skip_glob = [
    ".git",
    "__pycache__",
    "docs",
    "venv",
    "env",
    ".venv",
    ".env",
    "migrations",
    "alembic/versions"
]

[tool.ruff]
# Ruff linter configuration
line-length = 90
target-version = "py39"
exclude = [
    ".git",
    "__pycache__",
    "docs",
    "venv",
    "env",
    ".venv",
    ".env",
    "build",
    "dist",
    "migrations",
    "alembic/versions"
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C90", # mccabe complexity
    "UP",  # pyupgrade
]
ignore = [
    "E501", # line too long, handled by black
    "E203", # whitespace before ':'
]

[tool.mypy]
# MyPy type checker configuration
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
exclude = [
    "venv/",
    ".venv/",
    "env/",
    "migrations/",
    "alembic/versions/"
]
